### ISSUE TITLE
Example config.yaml?

### ISSUE THREAD

**Issue by FractumSeraph** [Dimildizio/Adjuface#4]
**Is your feature request related to a problem? Please describe.**
When building and running this project, it seems like it's trying to load a lot of information from a configuration file.  According to the instructions, only the bot token is needed in this file.

**Describe the solution you'd like**
An example of the config.yaml file.

**Describe alternatives you've considered**
I've tried reading the errors I get and manually adding that information to the config. (For example: 
`language: en`. But this method surely isn't the best.

**Comment by Dimildizio** [comment]
Added examples for config yaml and json files here:

https://github.com/Dimildizio/Adjuface/tree/main/docs/config_examples
